### ISSUE TITLE
Add Certificate to Router For Secure Login

### ISSUE THREAD

**Issue by Radicalius** [kngnm/network#11]

**Comment by kngnm** [comment]
Currently set up using self signed certificate.
Used this guide to set it up: [https://wiki.mikrotik.com/wiki/Manual:Hotspot_HTTPS_example](https://wiki.mikrotik.com/wiki/Manual:Hotspot_HTTPS_example)
Could potentially get a certificate signed by a real CA.  Would cost a little bit of money, but would prevent man in the middle attacks.  Probably not worth the trouble.
